In [36]:
import pandas as pd

### Q1. Pandas version

In [37]:
pd.__version__

'3.0.5'

In [38]:
df = pd.read_csv("car_fuel_efficiency_2026.csv")
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

### Q2. Records count

In [39]:
df.count()

model_year             10000
origin                 10000
fuel_type              10000
drivetrain             10000
num_doors              10000
engine_displacement    10000
num_cylinders          10000
horsepower              9123
vehicle_weight         10000
acceleration            9736
fuel_efficiency_mpg    10000
dtype: int64

### Q3. Fuel types

In [40]:
df.nunique()

model_year              50
origin                   3
fuel_type                3
drivetrain               3
num_doors                4
engine_displacement    127
num_cylinders            5
horsepower             153
vehicle_weight         176
acceleration            93
fuel_efficiency_mpg    188
dtype: int64

### Q4. Missing values

In [41]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

### Q5. Max fuel efficiency

In [42]:
df['fuel_efficiency_mpg'].max()

np.float64(41.2)

### Q6. Median value of horsepower

In [43]:
df['horsepower'].median()

np.float64(254.0)

In [44]:
df['horsepower'].mode()

0    252.0
Name: horsepower, dtype: float64

In [45]:
df.fillna(252.0)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,252.0,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,252.0,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2
9999,2011,USA,Diesel,Front-wheel drive,4,2380,6,295.0,4370,17.6,30.2

In [46]:
df['horsepower'].median()

np.float64(254.0)

### Q7. Sum of weights

In [48]:
df = df[
    df['origin'] == 'Asia'
]

In [52]:
df = df[['vehicle_weight', 'model_year']]

In [54]:
df = df.head(7)
df

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [51]:
import numpy as np

In [58]:
X = df.values
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [84]:
X_T = X.T
XTX = X_T.dot(X)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [87]:
XTX = np.linalg.inv(XTX)

In [88]:
y = [1100, 1300, 800, 900, 1000, 1100, 1200]

In [89]:
w = XTX.dot(X.T)
w = w.dot(y)
w

array([0.13644777, 0.2327492 ])

In [90]:
w.sum()

np.float64(0.36919696904925486)